manifest:
  version: 1.0

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.3.0
      import:
        name-allowlist:
          - cmsis_6
          - hal_espressif
          - hal_nordic
          - nrf_hw_models
        path-prefix: deps
